arch: UNext
batch_size: 16
cfg: null
dataset: busi
deep_supervision: false
early_stopping: -1
epochs: 200
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 256
input_w: 256
loss: BCEDiceLoss
lr: 0.01
mask_ext: .png
milestones: 1,2
min_lr: 0.0001
momentum: 0.9
name: busi_UNext_woDS
nesterov: false
num_classes: 1
num_workers: 4
optimizer: Adam
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
